### ISSUE TITLE
Errors when launching getMultiPrimerSet

### ISSUE THREAD

**Issue by DrownedMala** [SemiQuant/PrimerJinn#5]
Hello dear developers,

Today, I installed your tool as per instructions and it did install properly. I had already installed BLAST+ suite earlier on.

As per object, I was trying to launch getMultiPrimerSet for the first time, and I got the below error message:

```
Traceback (most recent call last):
  File "/home/simone/miniconda3/bin/getMultiPrimerSet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/simone/miniconda3/lib/python3.11/site-packages/primerJinn/getMultiPrimerSet.py", line 356, in main
    df = pd.read_excel(file_path, engine='openpyxl') 
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/simone/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/.local/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 553, in __init__
    super().__init__(
  File "/home/simone/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 573, in __init__
    self.book = self.load_workbook(self.handles.handle, engine_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/.local/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 572, in load_workbook
    return load_workbook(
           ^^^^^^^^^^^^^^
  File "/home/simone/.local/lib/python3.11/site-packages/openpyxl/reader/excel.py", line 344, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/.local/lib/python3.11/site-packages/openpyxl/reader/excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/.local/lib/python3.11/site-packages/openpyxl/reader/excel.py", line 95, in _validate_archive
    archive = ZipFile(filename, 'r')
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/miniconda3/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/home/simone/miniconda3/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

```

The line of code I used is:

```
getMultiPrimerSet --Q5 --product_size_max 600 --product_size_min 350 --region_file region_file.bed --input_file input_file.fna --output output_name
```

I was trying to build primers for a genome of ~44.4Mb, namely [Strongyloides stercoralis](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_029582065.1/).

Could you point me towards the possible cause and maybe a solution? 
Thanks in advance!

Simone

**Comment by adbeggs** [comment]
I had the same problem, and fixed this by using an region file with the name TSV rather than BED..

The other problem now is that there are conflicts between scikit-learn and python in the latest versions
