### ISSUE TITLE
ValueError: More than one record found in handle

### ISSUE THREAD

**Issue by alexlenail** [SemiQuant/PrimerJinn#7]
I'm trying to conduct an in silico PCR with a multiplex primer set, looking for non-specific amplification in the mouse transcriptome. The mouse transcriptome fasta contains multiple records (per transcript) but PrimerJinn fails when the mouse transcriptome fasta is provided as a reference: 

```
Traceback (most recent call last):
  File "/Users/alex/miniforge3/envs/py311/bin/PCRinSilico", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/alex/miniforge3/envs/py311/lib/python3.11/site-packages/primerJinn/PCRinSilico.py", line 211, in main
    ref_seq = SeqIO.read(ref_fasta_file, "fasta").seq
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/miniforge3/envs/py311/lib/python3.11/site-packages/Bio/SeqIO/__init__.py", line 667, in read
    raise ValueError("More than one record found in handle")
ValueError: More than one record found in handle
```

**Comment by rfinkers** [comment]
running into the same issue here. Looks like no easy fix forward :(.

Reason: the SeqIO.read function expects one sequence, not a multi-fasta. The provided example also only contains one sequence (in ref.fa). Updating this functionality to handling a multi-fasta probably is not trivial. Making it hard to use the tool.
