### ISSUE TITLE
Primer sites not corresponding to target regions??

### ISSUE THREAD

**Issue by jeanlain** [SemiQuant/PrimerJinn#9]
Hello, I tried to design primers pairs targeting very close regions that are 300-bp appart.
Here are the regions : 

> 
![image](https://github.com/user-attachments/assets/2d795944-0ea5-4b37-84e2-55a2e384bbd1)

My fasta is about 14kb (it's a mitochondrial genome, it's the full size). 
I initially got errors when running getMultiPrimerSet. 
Here is the function call:
`getMultiPrimerSet --region_file primer_regions.tsv --input_file ../Desktop/test.fas --target_tm 60 --primer_len 20 --product_size_min 200 --product_size_max 500 --ret 100 --background "" --output example`

Here's what the terminal showed:

> 
> [...]
> Picking initial primers for Target 5200-5220
> Picking initial primers for Target 5500-5520
> Picking initial primers for Target 5800-5820
> Picking initial primers for Target 6100-6120
> Picking initial primers for Target 6400-6420
> Picking initial primers for Target 6700-6720
> Picking initial primers for Target 7000-7020
> Issue setting globals. bytes provided: 
> 	
> 
>b'PRIMER_MIN_GC=40\nPRIMER_MAX_GC=80\nPRIMER_NUM_RETURN=100\nPRIMER_EXPLAIN_FLAG=1\nPRIMER_MIN_TM=57.0\nPRIMER_OPT_TM=60.0\nPRIMER_MAX_TM=63.0\nPRIMER_PRODUCT_SIZE_RANGE=200-500\nPRIMER_INTERNAL_MAX_POLY_X=3\nPRIMER_SALT_DIVALENT=2\nPRIMER_SALT_MONOVALENT=70\nPRIMER_DNA_CONC=3300\nPRIMER_TM_FORMULA=1\nPRIMER_SALT_CORRECTIONS=2\nSEQUENCE_ID=23BVR06_asm_k127_365647\nSEQUENCE_TEMPLATE=GCAAGCAAGCAAGCTCAA[...]ATAAATTATTTATAAGTGAGGG\nSEQUENCE_TARGET=6999,20\nPRIMER_OPT_SIZE=20\nPRIMER_MIN_SIZE=10\nPRIMER_MAX_SIZE=36\nPRIMER_PICK_INTERNAL_OLIGO=0\nPRIMER_MISPRIMING_LIBRARY=/var/folders/nb/2v97x4m52zj90h0nmvs2r98c0000gn/T/tmppfn25i8v/no_back.fasta\n=\n'
> Traceback (most recent call last):
>  File "/usr/local/bin/getMultiPrimerSet", line 8, in <module>
>  sys.exit(main())
> File "/usr/local/lib/python3.9/site-packages/primerJinn/getMultiPrimerSet.py", line 473, in main
>  primer_tmp = design_primers(
> File "/usr/local/lib/python3.9/site-packages/primerJinn/getMultiPrimerSet.py", line 158, in design_primers
>  primers = primer3.bindings.design_primers(input_params, global_args)
>  File "/usr/local/lib/python3.9/site-packages/primer3/bindings.py", line 550, in design_primers
>  return THERMO_ANALYSIS.run_design(
> File "primer3/thermoanalysis.pyx", line 1275, in primer3.thermoanalysis._ThermoAnalysis.run_design
> File "primer3/thermoanalysis.pyx", line 1203, in primer3.thermoanalysis._ThermoAnalysis._set_globals_and_seq_args
> File "primer3/thermoanalysis.pyx", line 1184, in primer3.thermoanalysis._ThermoAnalysis._set_globals_and_seq_args
> File "primer3/thermoanalysis.pyx", line 1439, in primer3.thermoanalysis.pdh_wrap_set_seq_args_globals
> ValueError: Empty sequence in mispriming library /var/folders/nb/2v97x4m52zj90h0nmvs2r98c0000gn/T/tmppfn25i8v/no_back.fasta

So it looks like it was failing after region 7000-7020. 
After increasing the length of the fasta by duplicating the sequence, I got the program running, but the results are strange. The primer binding site coordinates don't match to the targets.

For instance: 

> 
![image](https://github.com/user-attachments/assets/9dc93551-d084-48cf-86cb-086394e1a01d)

"Target 7000-7020" is associated with pair of primers with binding sites that go beyond 14000!

So it seems the program tries to find primers in regions that are far beyond the specified targets, hence the bug I was having when the fasta was 14 kb.

**Comment by SemiQuant** [comment]
hmm, thats not good. I must have broken something while trying to update. Could you send me your files to use for testing fixes please. Also, when running don't add --background "" else its looking for a file that's empty, causing issues (this may be why its designing in the incorrect place.

**Comment by SemiQuant** [comment]
I made a possible fix if you'd like to try it.

```
git clone https://github.com/SemiQuant/PrimerJinn.git
cd PrimerJinn
python -m build
pip install .
```

**Comment by karlkashofer** [comment]
Hi ! 
I have also seen this problem and have now tested the overlaps_and_regions branch.
I can confirm that the problem with the too-short input sequence is fixed, it does not complain about the input sequence and after primer design the locations given in the result are correct.

However, i would like to use the [humrep_and_simple.txt](https://primer3.ut.ee/primer3web_help.htm#providedMisprimingLibs) mispriming library from primer3 and as soon as i include that PrimerJinn finds no targets any more.
`python3 /PrimerJinn/PrimerJinn/getMultiPrimerSet.py --region_file ./regions.tsv --input_file ./template.fasta --target_tm 65     --primer_len 20     --product_size_min 40     --product_size_max 160     --ret 100 --output MultiPlexPrimerSet --no_self_background --background ./humrep_and_simple.txt`
always results in "no targets found". Any idea what could be wrong ?

Lastly, it seems PrimerJinn is not using the target name from the "name" column in regions.tsv. Is that on purpose ? Why ?

Thanks a lot for this cool project !
